name: Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: yarn
      - name: js|jsx|ts|tsx|cjs|mjs
        run: yarn lint
      - name: html
        run: yarn lint:html
      - name: json
        run: yarn lint:json
      - name: md
        run: yarn lint:md
      - name: package
        run: yarn lint:package
      - name: yml
        run: yarn lint:yml
